### PR TITLE
made smaller to fit project goal

### PR DESCRIPTION
**Pull request by keetron**
removed the lines that add fluff, as per your project goal

### CODE REVIEW

**Comment by WebReflection** [comment]
that's not fluff, that's the plain bare minimum output that reflects open collective one and gives a meaning to the logo.

This package in its entirety is less than 4KB, the goal is reached.

**Comment by WebReflection** [comment]
Project goal updated: https://github.com/WebReflection/lightercollective#project-goal

**Comment by keetron** [comment]
Heh, I figured asking for donation in about a quarter of the lines of code a bit cheeky. But of course, as you wish.

**Comment by WebReflection** [comment]
what is your issue with this, exactly? It's the least invasive approach [opencollective-cli](https://github.com/opencollective/opencollective-cli/blob/master/src/commands/postinstall-plain.js) offers + it avoids downloading 24MB of cli to serve the [rich version](https://github.com/opencollective/opencollective-cli/blob/master/src/commands/postinstall-rich.js) and much more.

What do you find cheeky in an Open Source project that would like to be sustainable?

Or having a link in console for something developed and tested is too much to deal with?

**Comment by keetron** [comment]
It seems we disagree fundamentally on what it means when ones says: As
small as possible, and then even less.
Let's agree to leave it at that.

**Comment by WebReflection** [comment]
I’ve updated the project goal to avoid extreme misunderstanding from people that would remove copy rights and a link to donate from this script that is a replacement of a 24MB cli.

**Pull request closed without merging**
