### PR TITLE
Do no harm

### PR DESCRIPTION
**Pull request by mattezell**
Update the usage examples to demonstrate using opencollective/lightercollective in a manner that won't cause other things to fail in the event that opencollective/lightercollective fails (as can happen in some CI and offline scenarios). Arguably, displaying a banner soliciting project funding shouldn't cause downstream operations to fail in projects using a library that uses opencollective/lightercollective.

### CODE REVIEW

**Comment by WebReflection** [comment]
In which case would it fail, exactly? There's also a flag to skip it directly.

If I configure something I think I want to know if something failed.

Do you have an example of issues?

**Comment by mattezell** [comment]
Yes. https://github.com/webpack/webpack-cli/issues/738

As you can see, they've completely removed their dependence on lightercollective as a result of this issue.

At the end of the day, a banner soliciting money, which isn't a functional concern of the project using libraries that use lightercollective, shouldn't break the functionality of the consuming project - which, in some cases, it currently does. 

As is discussed in the previously shared links on the other document-register-element request, it seems the most common failure scenarios are around CI environments and environments where non-standard node/npm installations are present. I am very much experiencing this issue now in an enterprise build api system - and so we're currently evaluating alternatives to libraries, such as document-register-element, that lead to failures of this sort (which is unfortunate when considering that a simple "|| exit 0" is all that's required in libraries using lightercollective to prevent this failure altogether).

**Comment by WebReflection** [comment]
> As you can see, they've completely removed their dependence on lightercollective as a result of this issue.

all I see there is Open Source done wrong, to be honest.

> At the end of the day, a banner soliciting money, which isn't a functional concern of the project using libraries that use lightercollective, shouldn't break the functionality of the consuming project - which, in some cases, it currently does.

I agree on this statement, which is why I've pushed `0.3.0` that should never fail.

That's how I fix software issues, not by exiting with `0` ... I want to know, if something went wrong, what went wrong via software, not via system fallbacks that ignore the error.

> it seems the most common failure scenarios are around CI environments and environments where non-standard node/npm installations are present

I'd like to know, since there's no way to reproduce the issue, if `0.3.0` would fail too.

A good bug report usually provides a reproducible test case.

> so we're currently evaluating alternatives to libraries ...

in case of DRE, good luck with that (there are no alternatives), but in general, I suggest you folks file better bugs to projects that help your business.

**Comment by WebReflection** [comment]
I assume the update worked.

**Comment by mattezell** [comment]
Not necessarily, but I did find a solution elsewhere which I've disclosed in the DRE discussion: https://github.com/WebReflection/document-register-element/pull/165

To those who may stumble here, I'd suggest reviewing the linked DRE discussion - specifically the part regarding multiple path casings on process.env in Windows environments, which will raise this error. I do still believe that recommending projects that use this project add "|| exit 0" to their postinstall, as opencollective has done (https://github.com/nuxt/opencollective) to prevent this identical failure, but of course that's your choice as the author and sole maintainer.

Thanks again!

**Pull request closed without merging**
